version: "3.3"
services:

  backend:
    image: in-memory:1.0
    ports:
      - 80:8080
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

    command: bash start.sh

    volumes:
      - './:/app'