"""empty message

Revision ID: 1d104524f52c
Revises: 48856b89892a
Create Date: 2022-08-26 02:00:35.521799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d104524f52c'
down_revision = '48856b89892a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compartiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('vehicule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compartiment_id'), 'compartiment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compartiment_id'), table_name='compartiment')
    op.drop_table('compartiment')
    # ### end Alembic commands ###
