"""initial

Revision ID: 3d98f19aa535
Revises: 
Create Date: 2022-08-25 12:48:29.434149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d98f19aa535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depot_id'), 'depot', ['id'], unique=False)
    op.create_table('fournisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fournisseur_id'), 'fournisseur', ['id'], unique=False)
    op.create_table('typeproduit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typeproduit_id'), 'typeproduit', ['id'], unique=False)
    op.create_table('commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commande_id'), 'commande', ['id'], unique=False)
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['typeproduit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produit_id'), 'produit', ['id'], unique=False)
    op.create_table('association_fournisseur_produit',
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('produit_id', 'fournisseur_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_fournisseur_produit')
    op.drop_index(op.f('ix_produit_id'), table_name='produit')
    op.drop_table('produit')
    op.drop_index(op.f('ix_commande_id'), table_name='commande')
    op.drop_table('commande')
    op.drop_index(op.f('ix_typeproduit_id'), table_name='typeproduit')
    op.drop_table('typeproduit')
    op.drop_index(op.f('ix_fournisseur_id'), table_name='fournisseur')
    op.drop_table('fournisseur')
    op.drop_index(op.f('ix_depot_id'), table_name='depot')
    op.drop_table('depot')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
