"""empty message

Revision ID: 479fea645d6a
Revises: d4ecfd73c06f
Create Date: 2022-10-08 20:29:01.749689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479fea645d6a'
down_revision = 'd4ecfd73c06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('compartiment_vehicule_id_fkey', 'compartiment', type_='foreignkey')
    op.create_foreign_key(None, 'compartiment', 'vehicule', ['vehicule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('holdedorder_commande_id_fkey', 'holdedorder', type_='foreignkey')
    op.create_foreign_key(None, 'holdedorder', 'commande', ['commande_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vehicule_depot_id_fkey', 'vehicule', type_='foreignkey')
    op.create_foreign_key(None, 'vehicule', 'depot', ['depot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicule', type_='foreignkey')
    op.create_foreign_key('vehicule_depot_id_fkey', 'vehicule', 'depot', ['depot_id'], ['id'])
    op.drop_constraint(None, 'holdedorder', type_='foreignkey')
    op.create_foreign_key('holdedorder_commande_id_fkey', 'holdedorder', 'commande', ['commande_id'], ['id'])
    op.drop_constraint(None, 'compartiment', type_='foreignkey')
    op.create_foreign_key('compartiment_vehicule_id_fkey', 'compartiment', 'vehicule', ['vehicule_id'], ['id'])
    # ### end Alembic commands ###
