"""empty message

Revision ID: 48856b89892a
Revises: 8c2a06807a95
Create Date: 2022-08-26 01:28:05.680380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48856b89892a'
down_revision = '8c2a06807a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_commande_chargee',
    sa.Column('vehicule.id', sa.Integer(), nullable=False),
    sa.Column('commande.id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande.id'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['vehicule.id'], ['vehicule.id'], ),
    sa.PrimaryKeyConstraint('vehicule.id', 'commande.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_commande_chargee')
    # ### end Alembic commands ###
