"""empty message

Revision ID: 554aee2ba382
Revises: 
Create Date: 2022-09-07 15:32:48.412815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554aee2ba382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('depot',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depot_id'), 'depot', ['id'], unique=False)
    op.create_table('fournisseur',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('time_service', sa.Integer(), nullable=True),
    sa.Column('time_interval_start', sa.Integer(), nullable=True),
    sa.Column('time_interval_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fournisseur_id'), 'fournisseur', ['id'], unique=False)
    op.create_table('typeproduit',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typeproduit_id'), 'typeproduit', ['id'], unique=False)
    op.create_table('produit',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['typeproduit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produit_id'), 'produit', ['id'], unique=False)
    op.create_table('vehicule',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('nb_compartment', sa.Integer(), nullable=True),
    sa.Column('size_compartment', sa.Integer(), nullable=True),
    sa.Column('cout', sa.Integer(), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('trajet', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicule_id'), 'vehicule', ['id'], unique=False)
    op.create_table('association_fournisseur_produit',
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('produit_id', 'fournisseur_id')
    )
    op.create_table('commande',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('qty_fixed', sa.Integer(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commande_id'), 'commande', ['id'], unique=False)
    op.create_table('compartiment',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compartiment_id'), 'compartiment', ['id'], unique=False)
    op.create_table('holdedorder',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('compartiment_id', sa.Integer(), nullable=False),
    sa.Column('qty_holded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['compartiment_id'], ['compartiment.id'], ),
    sa.PrimaryKeyConstraint('commande_id', 'compartiment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdedorder')
    op.drop_index(op.f('ix_compartiment_id'), table_name='compartiment')
    op.drop_table('compartiment')
    op.drop_index(op.f('ix_commande_id'), table_name='commande')
    op.drop_table('commande')
    op.drop_table('association_fournisseur_produit')
    op.drop_index(op.f('ix_vehicule_id'), table_name='vehicule')
    op.drop_table('vehicule')
    op.drop_index(op.f('ix_produit_id'), table_name='produit')
    op.drop_table('produit')
    op.drop_index(op.f('ix_typeproduit_id'), table_name='typeproduit')
    op.drop_table('typeproduit')
    op.drop_index(op.f('ix_fournisseur_id'), table_name='fournisseur')
    op.drop_table('fournisseur')
    op.drop_index(op.f('ix_depot_id'), table_name='depot')
    op.drop_table('depot')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
