"""empty message

Revision ID: 67adb7ae0a12
Revises: 3d98f19aa535
Create Date: 2022-08-25 16:18:27.292436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67adb7ae0a12'
down_revision = '3d98f19aa535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commande', sa.Column('produit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commande', 'produit', ['produit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commande', type_='foreignkey')
    op.drop_column('commande', 'produit_id')
    # ### end Alembic commands ###
