"""empty message

Revision ID: 68601acb67ff
Revises: baabf802ce7c
Create Date: 2022-08-26 13:00:36.150930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68601acb67ff'
down_revision = 'baabf802ce7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
