"""empty message

Revision ID: 688aa146dd5c
Revises: d33f49a13db9
Create Date: 2022-09-07 03:01:29.846272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688aa146dd5c'
down_revision = 'd33f49a13db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
