"""empty message

Revision ID: 72dfb33aac53
Revises: 8cd95f306b7e
Create Date: 2022-09-07 03:36:40.719395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dfb33aac53'
down_revision = '8cd95f306b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commande', 'produit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commande', 'produit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
