"""empty message

Revision ID: 74c563031e58
Revises: 25ed514f2187
Create Date: 2022-08-26 07:11:51.908030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c563031e58'
down_revision = '25ed514f2187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdedorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('compartiment_id', sa.Integer(), nullable=False),
    sa.Column('qty_holded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['compartiment_id'], ['compartiment.id'], ),
    sa.PrimaryKeyConstraint('id', 'commande_id', 'compartiment_id')
    )
    op.create_index(op.f('ix_holdedorder_id'), 'holdedorder', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdedorder_id'), table_name='holdedorder')
    op.drop_table('holdedorder')
    # ### end Alembic commands ###
