"""empty message

Revision ID: 7606ced7eba0
Revises: 7b90d6f066d8
Create Date: 2022-08-26 07:07:56.559405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7606ced7eba0'
down_revision = '7b90d6f066d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_holdedorder_id', table_name='holdedorder')
    op.drop_table('holdedorder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdedorder',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('commande_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('compartiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_holded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commande.id'], name='holdedorder_commande_id_fkey'),
    sa.ForeignKeyConstraint(['compartiment_id'], ['compartiment.id'], name='holdedorder_compartiment_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'commande_id', 'compartiment_id', name='holdedorder_pkey')
    )
    op.create_index('ix_holdedorder_id', 'holdedorder', ['id'], unique=False)
    # ### end Alembic commands ###
