"""empty message

Revision ID: 7b90d6f066d8
Revises: c1f779a13160
Create Date: 2022-08-26 07:00:38.534257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b90d6f066d8'
down_revision = 'c1f779a13160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
