"""empty message

Revision ID: 8c2a06807a95
Revises: 67adb7ae0a12
Create Date: 2022-08-26 01:17:54.177947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2a06807a95'
down_revision = '67adb7ae0a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('nb_compartment', sa.Integer(), nullable=True),
    sa.Column('size_compartment', sa.Integer(), nullable=True),
    sa.Column('cout', sa.Integer(), nullable=True),
    sa.Column('trajet', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicule_id'), 'vehicule', ['id'], unique=False)
    op.add_column('client', sa.Column('code', sa.String(), nullable=True))
    op.add_column('depot', sa.Column('code', sa.String(), nullable=True))
    op.add_column('fournisseur', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fournisseur', 'code')
    op.drop_column('depot', 'code')
    op.drop_column('client', 'code')
    op.drop_index(op.f('ix_vehicule_id'), table_name='vehicule')
    op.drop_table('vehicule')
    # ### end Alembic commands ###
