"""empty message

Revision ID: 8cd95f306b7e
Revises: 688aa146dd5c
Create Date: 2022-09-07 03:02:12.359620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd95f306b7e'
down_revision = '688aa146dd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
