"""empty message

Revision ID: 9e8fcd3b7414
Revises: 1d104524f52c
Create Date: 2022-08-26 06:29:42.245309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8fcd3b7414'
down_revision = '1d104524f52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_commande_chargee', sa.Column('qty_holded', sa.Integer(), nullable=True))
    op.drop_constraint('association_commande_chargee_vehicule.id_fkey', 'association_commande_chargee', type_='foreignkey')
    op.drop_column('association_commande_chargee', 'vehicule.id')
    op.drop_column('association_commande_chargee', 'qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_commande_chargee', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('association_commande_chargee', sa.Column('vehicule.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('association_commande_chargee_vehicule.id_fkey', 'association_commande_chargee', 'vehicule', ['vehicule.id'], ['id'])
    op.drop_column('association_commande_chargee', 'qty_holded')
    # ### end Alembic commands ###
