"""empty message

Revision ID: aaa4675ecedf
Revises: 479fea645d6a
Create Date: 2022-10-08 20:30:30.942685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa4675ecedf'
down_revision = '479fea645d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commande_produit_id_fkey', 'commande', type_='foreignkey')
    op.create_foreign_key(None, 'commande', 'produit', ['produit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('holdedorder_compartiment_id_fkey', 'holdedorder', type_='foreignkey')
    op.create_foreign_key(None, 'holdedorder', 'compartiment', ['compartiment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdedorder', type_='foreignkey')
    op.create_foreign_key('holdedorder_compartiment_id_fkey', 'holdedorder', 'compartiment', ['compartiment_id'], ['id'])
    op.drop_constraint(None, 'commande', type_='foreignkey')
    op.create_foreign_key('commande_produit_id_fkey', 'commande', 'produit', ['produit_id'], ['id'])
    # ### end Alembic commands ###
