"""empty message

Revision ID: ab0bcf413b45
Revises: 74c563031e58
Create Date: 2022-08-26 07:18:36.452727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0bcf413b45'
down_revision = '74c563031e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_holdedorder_id', table_name='holdedorder')
    op.drop_column('holdedorder', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdedorder', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_holdedorder_id', 'holdedorder', ['id'], unique=False)
    # ### end Alembic commands ###
