"""empty message

Revision ID: ab2a98c96d30
Revises: aaa4675ecedf
Create Date: 2022-10-08 20:31:40.893438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2a98c96d30'
down_revision = 'aaa4675ecedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compartiment', 'vehicule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compartiment', 'vehicule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
