"""empty message

Revision ID: baabf802ce7c
Revises: d2f2910ae6f2
Create Date: 2022-08-26 09:06:51.515733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baabf802ce7c'
down_revision = 'd2f2910ae6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
