"""empty message

Revision ID: be68997d6366
Revises: 16939d5cc2db
Create Date: 2022-09-07 02:48:37.029705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be68997d6366'
down_revision = '16939d5cc2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compartiment', 'vehicule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compartiment', 'vehicule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
