"""empty message

Revision ID: c1f779a13160
Revises: 9e8fcd3b7414
Create Date: 2022-08-26 06:52:39.341109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f779a13160'
down_revision = '9e8fcd3b7414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_commande_chargee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_commande_chargee',
    sa.Column('commande.id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_holded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commande.id'], ['commande.id'], name='association_commande_chargee_commande.id_fkey')
    )
    # ### end Alembic commands ###
