"""empty message

Revision ID: d2f2910ae6f2
Revises: ab0bcf413b45
Create Date: 2022-08-26 09:01:30.895938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f2910ae6f2'
down_revision = 'ab0bcf413b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
