"""empty message

Revision ID: d33f49a13db9
Revises: be68997d6366
Create Date: 2022-09-07 02:56:23.260426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33f49a13db9'
down_revision = 'be68997d6366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
