"""empty message

Revision ID: d4ecfd73c06f
Revises: c20c5415c00a
Create Date: 2022-10-08 19:21:11.768762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ecfd73c06f'
down_revision = 'c20c5415c00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commande_client_id_fkey', 'commande', type_='foreignkey')
    op.drop_constraint('commande_fournisseur_id_fkey', 'commande', type_='foreignkey')
    op.create_foreign_key(None, 'commande', 'fournisseur', ['fournisseur_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commande', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commande', type_='foreignkey')
    op.drop_constraint(None, 'commande', type_='foreignkey')
    op.create_foreign_key('commande_fournisseur_id_fkey', 'commande', 'fournisseur', ['fournisseur_id'], ['id'])
    op.create_foreign_key('commande_client_id_fkey', 'commande', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
