"""empty message

Revision ID: e98d1e50261d
Revises: 552fc4f5ea29
Create Date: 2022-08-27 03:07:17.157098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98d1e50261d'
down_revision = '552fc4f5ea29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
